name: Mirror Repo for Deployment

on:
  push:
    branches: [ "main", "fix-deployment" ]

jobs:
  mirror-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: echo "api\nspecial_stuff" > .vercelignore
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:chasemcdo/ECE444-app-deployment.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}

  mirror-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:chasemcdo/ECE444-backend-deployment.git
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
