name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
          version: latest
          run_install: true

    - name: TS Test
      run: pnpm next-test

    - name: Python Test
      run: pnpm flask-test
